default:
	python3 compress.py Compressed/pic.jpg
	python3 compress.py Compressed/absolute.pdf
	python3 compress.py Compressed/README
	python3 compress.py Compressed/test.txt

move:
	mv Compressed/pic.jpg.huf wwwroot/
	mv Compressed/absolute.pdf.huf wwwroot/
	mv Compressed/README.huf wwwroot/
	mv Compressed/test.txt.huf wwwroot/