PROGRAM = freq.py

test1:
	python3 $(PROGRAM) sample0
test2:
	python3 $(PROGRAM) sample1
test3:
	python3 $(PROGRAM) sample2

all:
	python3 $(PROGRAM) sample0
	python3 $(PROGRAM) sample1
	python3 $(PROGRAM) sample2