# Makefile for Moneybags Assignment
# Ryan Sandoval, 1529017, CMPUT 274 Fall 2018

moneybags.out: moneybags.cpp
	g++ moneybags.cpp -o moneybags.out -Wall

run:
	./moneybags.out

clean: 
	rm moneybags.out
